import type { Metadata } from "next";
import { Inter, Lobster } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/page"
import Footer from "@/components/footer/page";
import {ThemeProvider} from "@/context/ThemeContext"

const BodyFont = Lobster({ subsets: ["latin"],
weight : "400"
 });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      
        <body className={BodyFont.className} >
        <ThemeProvider>
        <Navbar />
        {children}
        
        <Footer/>
        </ThemeProvider>
        </body>


    </html>
    
  );
}
